### ISSUE TITLE
:transform is not implemented on writer

### ISSUE THREAD

**Issue by wilkerlucio** [cognitect/transit-cljs#48]
I was trying to use the `:transform` feature from the writer but seems like it's not implemented in the CLJS version, this is an example code using Clojure transit (this works):

```clojure
(let [x (with-meta [:a] {:foo "bar"})
        baos (ByteArrayOutputStream.)
        w    (transit/writer baos :json {:transform transit/write-meta})
        _    (transit/write w x)
        ret  (.toString baos)]
    (.reset baos)
    ret)
=> "[\"~#with-meta\",[[\"~:a\"],[\"^ \",\"~:foo\",\"bar\"]]]"
```

But doing a similar run in CLJS yields:

```clojure
(-> (transit/writer :json {:transform transit/write-meta}) 
      (transit/write (with-meta [:a] {:foo "data"})))
=> "[\"~:a\"]"
```

The docs on CLJS suggest this should work. So I guess it was copied the docs but never implemented?

**Comment by wilkerlucio** [comment]
I just noticed my `transit-js` lib was outdated, forcing it to the latest fixed the issue.

**Comment by awb99** [comment]
I just came into the same issue. Something is broken in the CI / build system. the latest transit-cljs artefact has an old transit-js dependency. This should not happen. As it is now, write-meta will only work if additionally the latest transit-js is added as dependency. I think CI is broken, because source code in github and artefacts in maven are different version numbers.

**Comment by swannodette** [comment]
@awb99 more information would be help - what is the discrepancy in the versions? The pom.xml and project.clj are of course pointing at the latest.
